project:
  type: website
  output-dir: docs

website:
  title: "Amie Liu"
  favicon: img/amielogo.png

  navbar:
    pinned: true
    logo: /img/logo.png
    
    # sub-pages  
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - myworks.qmd
  
  page-footer:
    center: 
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "My Works"
        href: myworks.qmd

format:
  html:
    theme: lux
    linkcolor: "#747264"
    css: styles.css
    toc: true

editor: visual

